//
//  IngredientEmojiProvider.swift
//  SmoothieSavvy
//
//  Created by Daniel Copley on 4/8/23.
//

import Foundation
import EmojiPicker

struct IngredientEmojiProvider: EmojiProvider {
    static let allEmojis = [
        Emoji(value: "🍏", name: "green apple"),
        Emoji(value: "🍎", name: "red apple"),
        Emoji(value: "🍐", name: "pear"),
        Emoji(value: "🍊", name: "orange"),
        Emoji(value: "🍋", name: "lemon"),
        Emoji(value: "🍌", name: "banana"),
        Emoji(value: "🍉", name: "watermelon"),
        Emoji(value: "🍇", name: "grape"),
        Emoji(value: "🍓", name: "strawberry"),
        Emoji(value: "🫐", name: "blueberry"),
        Emoji(value: "🍈", name: "melon"),
        Emoji(value: "🍒", name: "cherry"),
        Emoji(value: "🍑", name: "peach"),
        Emoji(value: "🥭", name: "mango"),
        Emoji(value: "🍍", name: "pineapple"),
        Emoji(value: "🥥", name: "coconut"),
        Emoji(value: "🥝", name: "kiwi"),
        Emoji(value: "🍅", name: "tomato"),
        Emoji(value: "🍆", name: "egg plant"),
        Emoji(value: "🥑", name: "avocado"),
        Emoji(value: "🫛", name: "peas"),
        Emoji(value: "🥦", name: "broccoli"),
        Emoji(value: "🥬", name: "leafy greens"),
        Emoji(value: "🥒", name: "cucumber"),
        Emoji(value: "🌶️", name: "hot pepper"),
        Emoji(value: "🫑", name: "bell pepper"),
        Emoji(value: "🌽", name: "corn"),
        Emoji(value: "🥕", name: "carrot"),
        Emoji(value: "🫒", name: "olive"),
        Emoji(value: "🧄", name: "garlic"),
        Emoji(value: "🧅", name: "onion"),
        Emoji(value: "🥔", name: "potato"),
        Emoji(value: "🍠", name: "sweet potato"),
        Emoji(value: "🫚", name: "taco"),
        Emoji(value: "🥐", name: "croissant"),
        Emoji(value: "🥯", name: "bagel"),
        Emoji(value: "🍞", name: "bread"),
        Emoji(value: "🥖", name: "baguette"),
        Emoji(value: "🥨", name: "pretzel"),
        Emoji(value: "🧀", name: "cheese"),
        Emoji(value: "🥚", name: "egg"),
        Emoji(value: "🍳", name: "fried egg"),
        Emoji(value: "🧈", name: "butter"),
        Emoji(value: "🥞", name: "pancakes"),
        Emoji(value: "🧇", name: "waffle"),
        Emoji(value: "🥓", name: "bacon"),
        Emoji(value: "🥩", name: "steak"),
        Emoji(value: "🍗", name: "chicken"),
        Emoji(value: "🍖", name: "meat"),
        Emoji(value: "🦴", name: "bone"),
        Emoji(value: "🥗", name: "salad"),
        Emoji(value: "🫕", name: "stew"),
        Emoji(value: "🥫", name: "canned food"),
        Emoji(value: "🫙", name: "souvlaki"),
        Emoji(value: "🍝", name: "spaghetti"),
        Emoji(value: "🍜", name: "ramen"),
        Emoji(value: "🍲", name: "soup"),
        Emoji(value: "🍛", name: "curry"),
        Emoji(value: "🍣", name: "sushi"),
        Emoji(value: "🍱", name: "bento box"),
        Emoji(value: "🥟", name: "dumpling"),
        Emoji(value: "🦪", name: "oyster"),
        Emoji(value: "🍤", name: "fried shrimp"),
        Emoji(value: "🍙", name: "rice ball"),
        Emoji(value: "🍚", name: "cooked rice"),
        Emoji(value: "🍘", name: "rice cracker"),
        Emoji(value: "🍥", name: "fish cake"),
        Emoji(value: "🥮", name: "mooncake"),
        Emoji(value: "🍢", name: "oden"),
        Emoji(value: "🍡", name: "dango"),
        Emoji(value: "🍧", name: "shaved ice"),
        Emoji(value: "🍨", name: "ice cream"),
        Emoji(value: "🍦", name: "soft ice cream"),
        Emoji(value: "🥧", name: "pie"),
        Emoji(value: "🧁", name: "cupcake"),
        Emoji(value: "🍰", name: "cake"),
        Emoji(value: "🎂", name: "birthday cake"),
        Emoji(value: "🍮", name: "custard"),
        Emoji(value: "🍭", name: "lollipop"),
        Emoji(value: "🍬", name: "candy"),
        Emoji(value: "🍫", name: "chocolate"),
        Emoji(value: "🍿", name: "popcorn"),
        Emoji(value: "🍩", name: "doughnut"),
        Emoji(value: "🍪", name: "cookie"),
        Emoji(value: "🌰", name: "chestnut"),
        Emoji(value: "🥜", name: "peanut"),
        Emoji(value: "🫘", name: "beans"),
        Emoji(value: "🍯", name: "honey pot"),
        Emoji(value: "🥛", name: "glass of milk"),
        Emoji(value: "🫗", name: "teapot"),
        Emoji(value: "🍵", name: "teacup without handle"),
        Emoji(value: "🍶", name: "sake"),
        Emoji(value: "🍾", name: "bottle with popping cork"),
        Emoji(value: "🍷", name: "wine glass"),
        Emoji(value: "🍸", name: "cocktail glass"),
        Emoji(value: "🍹", name: "tropical drink"),
        Emoji(value: "🍺", name: "beer mug"),
        Emoji(value: "🍻", name: "clinking beer mugs"),
        Emoji(value: "🥂", name: "clinking glasses"),
        Emoji(value: "🥃", name: "tumbler glass"),
        Emoji(value: "🥤", name: "cup with straw"),
        Emoji(value: "🧃", name: "beverage box"),
        Emoji(value: "🧉", name: "mate drink"),
        Emoji(value: "🧊", name: "ice"),
        Emoji(value: "🥡", name: "takeout box"),
        Emoji(value: "🧂", name: "salt"),
        Emoji(value: "😀", name: "grinning face"),
        Emoji(value: "😃", name: "grinning face with big eyes"),
        Emoji(value: "😄", name: "grinning face with smiling eyes"),
        Emoji(value: "😁", name: "beaming face with smiling eyes"),
        Emoji(value: "😆", name: "grinning squinting face"),
        Emoji(value: "🥹", name: "person wearing turban"),
        Emoji(value: "😅", name: "grinning face with sweat"),
        Emoji(value: "😂", name: "face with tears of joy"),
        Emoji(value: "🤣", name: "rolling on the floor laughing"),
        Emoji(value: "🥲", name: "smiling face with tear"),
        Emoji(value: "☺️", name: "smiling face"),
        Emoji(value: "😊", name: "smiling face with smiling eyes"),
        Emoji(value: "😇", name: "smiling face with halo"),
        Emoji(value: "🙂", name: "slightly smiling face"),
        Emoji(value: "🙃", name: "upside-down face"),
        Emoji(value: "😉", name: "winking face"),
        Emoji(value: "😌", name: "relieved face"),
        Emoji(value: "😍", name: "smiling face with heart-eyes"),
        Emoji(value: "🥰", name: "smiling face with hearts"),
        Emoji(value: "😘", name: "face blowing a kiss"),
        Emoji(value: "😗", name: "kissing face"),
        Emoji(value: "😙", name: "kissing face with smiling eyes"),
        Emoji(value: "😚", name: "kissing face with closed eyes"),
        Emoji(value: "😋", name: "face savoring food"),
        Emoji(value: "😛", name: "face with tongue"),
        Emoji(value: "😝", name: "squinting face with tongue"),
        Emoji(value: "😜", name: "winking face with tongue"),
        Emoji(value: "🤪", name: "zany face"),
        Emoji(value: "🤨", name: "face with raised eyebrow"),
        Emoji(value: "🧐", name: "face with monocle"),
        Emoji(value: "🤓", name: "nerd face"),
        Emoji(value: "😎", name: "smiling face with sunglasses"),
        Emoji(value: "🥸", name: "disguised face"),
        Emoji(value: "🤩", name: "star-struck"),
        Emoji(value: "🥳", name: "partying face"),
        Emoji(value: "😏", name: "smirking face"),
        Emoji(value: "😒", name: "unamused face"),
        Emoji(value: "😞", name: "disappointed face"),
        Emoji(value: "😔", name: "pensive face"),
        Emoji(value: "😟", name: "worried face"),
        Emoji(value: "😕", name: "confused face"),
        Emoji(value: "🙁", name: "slightly frowning face"),
        Emoji(value: "☹️", name: "frowning face"),
        Emoji(value: "😣", name: "persevering face"),
        Emoji(value: "😖", name: "confounded face"),
        Emoji(value: "😫", name: "tired face"),
        Emoji(value: "😩", name: "weary face"),
        Emoji(value: "🥺", name: "pleading face"),
        Emoji(value: "😢", name: "crying face"),
        Emoji(value: "😭", name: "loudly crying face"),
        Emoji(value: "😤", name: "face with steam from nose"),
        Emoji(value: "😠", name: "angry face"),
        Emoji(value: "😡", name: "pouting face"),
        Emoji(value: "🤬", name: "face with symbols on mouth"),
        Emoji(value: "🤯", name: "exploding head"),
        Emoji(value: "😳", name: "flushed face"),
        Emoji(value: "🥵", name: "hot face"),
        Emoji(value: "🥶", name: "cold face"),
        Emoji(value: "😶‍🌫️", name: "face in clouds"),
        Emoji(value: "😱", name: "face screaming in fear"),
        Emoji(value: "😨", name: "fearful face"),
        Emoji(value: "😰", name: "anxious face with sweat"),
        Emoji(value: "😥", name: "sad but relieved face"),
        Emoji(value: "😓", name: "downcast face with sweat"),
        Emoji(value: "🤗", name: "hugging face"),
        Emoji(value: "🤔", name: "thinking face"),
        Emoji(value: "🫣", name: "face in clouds"),
        Emoji(value: "🤭", name: "face with hand over mouth"),
        Emoji(value: "🫢", name: "face with peeking eye"),
        Emoji(value: "🫡", name: "eye in speech bubble"),
        Emoji(value: "🤫", name: "shushing face"),
        Emoji(value: "🫠", name: "face with spiral eyes"),
        Emoji(value: "🤥", name: "lying face"),
        Emoji(value: "😶", name: "face without mouth"),
        Emoji(value: "🫥", name: "face with open eyes and hand over mouth"),
        Emoji(value: "😐", name: "neutral face"),
        Emoji(value: "🫤", name: "face with diagonal mouth"),
        Emoji(value: "😑", name: "expressionless face"),
        Emoji(value: "🫨", name: "face with diagonal mouth and open eyes"),
        Emoji(value: "😬", name: "grimacing face"),
        Emoji(value: "🙄", name: "face with rolling eyes"),
        Emoji(value: "😯", name: "hushed face"),
        Emoji(value: "😦", name: "frowning face with open mouth"),
        Emoji(value: "😧", name: "anguished face"),
        Emoji(value: "😮", name: "face with open mouth"),
        Emoji(value: "😲", name: "astonished face"),
        Emoji(value: "🥱", name: "yawning face"),
        Emoji(value: "😴", name: "sleeping face"),
        Emoji(value: "🤤", name: "drooling face"),
        Emoji(value: "😪", name: "sleepy face"),
        Emoji(value: "😮‍💨", name: "face exhaling"),
        Emoji(value: "😵", name: "dizzy face"),
        Emoji(value: "😵‍💫", name: "face with spiral eyes and dizzy face"),
        Emoji(value: "🤐", name: "zipper-mouth face"),
        Emoji(value: "🥴", name: "woozy face"),
        Emoji(value: "🤢", name: "nauseated face"),
        Emoji(value: "🤮", name: "vomit"),
        Emoji(value: "🤧", name: "sneezing"),
        Emoji(value: "😷", name: "mask"),
        Emoji(value: "🤒", name: "sick"),
        Emoji(value: "🤕", name: "injured"),
        Emoji(value: "🤑", name: "money"),
        Emoji(value: "🤠", name: "cowboy"),
        Emoji(value: "😈", name: "devil"),
        Emoji(value: "👿", name: "angry"),
        Emoji(value: "👹", name: "ogre"),
        Emoji(value: "👺", name: "goblin"),
        Emoji(value: "🤡", name: "clown"),
        Emoji(value: "💩", name: "poop"),
        Emoji(value: "👻", name: "ghost"),
        Emoji(value: "💀", name: "skull"),
        Emoji(value: "☠️", name: "skull and crossbones"),
        Emoji(value: "👽", name: "alien"),
        Emoji(value: "👾", name: "alien monster"),
        Emoji(value: "🤖", name: "robot"),
        Emoji(value: "🎃", name: "jack-o-lantern"),
        Emoji(value: "😺", name: "smiling cat"),
        Emoji(value: "😸", name: "grinning cat"),
        Emoji(value: "😹", name: "crying cat"),
        Emoji(value: "😻", name: "heart eyes cat"),
        Emoji(value: "😼", name: "smirking cat"),
        Emoji(value: "😽", name: "kissing cat"),
        Emoji(value: "🙀", name: "weary cat"),
        Emoji(value: "😾", name: "pouting cat")
    ]

    func getAll() -> [EmojiPicker.Emoji] {
        Self.allEmojis
    }
}
